# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

export EDITOR='vim'
export VISUAL='vim'
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git kubectl)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

#Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi


alias ll="ls -laG"
alias l="ls -laG"
alias g="git"
alias bit="git"
alias gp="git pull"
alias gbr="git branch"
alias gca="git ca"
alias gco="git checkout"
alias gd="git diff"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gcm="git commit -m"
alias ..="cd .."
alias tiempo="curl -4 wttr.in/Sevilla"
alias open="xdg-open"
alias glep="grep"
alias amend="git commit --amend -m"
alias lg="ll | grep "
alias ncat="ncat"
alias fuera="sudo pkill -9"
alias hgrep="history | grep "
alias ekca-ssh-init="$HOME/.venvs/osum_plus/bin/ekca-ssh-init"
alias davecli="$HOME/dev/daveapi/daveapi.py"
alias ekca="~/venvs/osum_plus/bin/ekca-ssh-init maguilararroyo"
alias gitree="git log --graph --oneline --all"
alias setdowntime="ssh goahead-prod-de-kae-bs01.server.lan sudo /srv/goahead/scripts/adddowntime.sh"
alias cic="clientinfocollector"
alias python="python3.12"
alias libreoffice="SAL_USE_VCLPLUGIN=gtk3 libreoffice"
alias ipspecial="ruby ~/bin/special_.rb"
export ANSIBLE_HOST_KEY_CHECKING=FALSE
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export SECSYSLOG_LIVE_CERT="/home/maguilar/dev/MI/itoct_teamstore_bin/certs/secsyslog-live-ca.pem"
#Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:/home/maguilar/pycharm-community-2024.1.1/bin"
export PATH="$PATH:/home/maguilar/.local/bin"

function ccssh() {
  servers=$(ndcli -q list rrs -H $1\* A | grep -Fv -- -repl | grep -Fv -- -t-e | grep -Fv transfer | grep -E "server.lan|ionos.tech" | cut -f1,2 | tr "\t" "." | tr "\n" " " )

  if [[ -n $servers ]];  then
        # https://stackoverflow.com/questions/16200142/zsh-parameter-expansion-inserting-quotes
        csshy -l maguilararroyo -t terminator -c $1 ${=servers:--maxdepth 1}
    else
        return $?
    fi
}
