---
- name: Set up repositories
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    repo: "{{ item.url }}"
    state: present
  loop: "{{ repos }}"

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_to_install }}"

- name: Install oh-my-zsh
  shell: "{{ oh_my_zsh_install_command }}"

- name: Set up zsh as default shell for user
  ansible.builtin.user:
    user: "{{ myuser }}"
    shell: "/bin/zsh"

- name: Copy .vimrc
  ansible.builtin.copy:
    src: "vimrc"
    dest: "/etc/vimrc"
- name: Copy .zshrc
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "/home/{{ myuser }}/.zshrc"

- name: Set up host entries
  ansible.builtin.template:
    src: "etc/hosts.j2"
    dest: "/etc/hosts"

- name: Sets up dnf5 auto update
  ansible.builtin.copy:
    src: "systemd/dnf5-automatic.timer"
    dest: "/usr/lib/systemd/system/dnf5-automatic.timer"
  notify: "systemctl reload"

- name: Enables dnf5 auto update
  ansible.builtin.systemd_service:
    name: dnf5-automatic.timer
    state: started
    enabled: true